services:
  postgres:
    image: 'postgres:latest'
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: database
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: admin
      LANG: en_US.utf8
      LC_ALL: en_US.utf8
    ports:
      - '5433:5432'
