spring.application.name=messenger-backend

spring.datasource.url=jdbc:postgresql://localhost:5433/database
spring.datasource.username=admin
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.servlet.multipart.max-file-size=8MB
spring.servlet.multipart.max-request-size=8MB

app.avatar-dir=${user.home}/messenger-uploads/avatars